### ISSUE TITLE
【Question】about “Risk-aware-contingency-planning-with-multi-modal-predictions ”paper

### ISSUE THREAD

**Issue by freeclouds** [KhMustafa/Risk-aware-contingency-planning-with-multi-modal-predictions#1]
hi ,i also study contingency planning,i can't find this paper“Risk-aware-contingency-planning-with-multi-modal-predictions ”,can you provide about this paper's  where can i get it,thanks!

**Comment by weilianzhen** [comment]
You can try this: RACP: Risk-Aware Contingency Planning with Multi-Modal Predictions.  I am also starting to learn related content.

**Comment by KhMustafa** [comment]
I have added the link to the paper to the readme file.
